### ISSUE TITLE
Wandb sweep hanging on Google Colab

### ISSUE THREAD

**Issue by isaacmg** [wandb/client#1243]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.10.1
* Python version: Python 3.6.9
* Operating System: Google Colab

### Description

Trying to run a sweep on Google Colab.

### What I Did

So there is no error the sweep just hangs indefinitely after the first run. 

```
wandb: Agent Finished Run
``
I then have to kill it manually 
```

wandb: Ctrl-c pressed. Waiting for runs to end. Press ctrl-c again to terminate them.
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/wandb_agent.py", line 69, in _start
    run._stop_jupyter_agent()
AttributeError: 'Run' object has no attribute '_stop_jupyter_agent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 261, in _bootstrap
    util._exit_function()
  File "/usr/lib/python3.6/multiprocessing/util.py", line 319, in _exit_function
    p.join()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 50, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```
This is true even on relatively simple things:
https://colab.research.google.com/drive/1u2xHJI_z-XoLTeFYGRzYS5PjdZGRakyG#scrollTo=HMRG0EnyyJYD

I also tested just using a generic train function with no model and it still fails.
https://colab.research.google.com/drive/1Ek-BpLf6BTXaZORGhgAi3NZo07mMw9nO#scrollTo=SAqGr4Vjp6ml

**Comment by vanpelt** [comment]
Hey @isaacmg we're aware of the issue.  With 0.10.1 you can use an experimental agent by replacing `wandb.agent` with `wandb_secretagent` which should fix the stalling issue.

**Comment by isaacmg** [comment]
Thanks. BTW for those wondering what the import statement looks like it is `from wandb.jupyteragent import jupyteragent as _secretagent`

**Comment by venti07** [comment]
I have the error also in Google Colab. Is there already a solution?

**Comment by NdePater** [comment]
I am still encountering this issue, and the _secretagent seems to be removed
