### ISSUE TITLE
Custom Charts: Slow performance when using ROC curve preset

### ISSUE THREAD

**Issue by stef-stripe** [wandb/client#1411]
A common use case I'd like to use wandb for is to store accuracy metrics across a number of experimental conditions and training bootstraps, and then compare those metrics faceted by experimental conditions, aggregating bootstraps as variance in the model performance.

I implemented a small demo of that [in this dashboard](https://wandb.ai/stef-stripe/binary-classification-2?workspace=user-stef-stripe), however the dashboard is incredibly slow for me; it takes 30s-1m to load the dashboard in a new tab, and normal interface usage like scrolling, clicking on panel elements, hovering, etc. often have a latency of 5+ seconds.

This is using wandb's `wandb.plot.roc_curve` on a relatively small number of models and a relatively small test set (the ROC tables have 178 values in them each, which is less fine-grained than I'd normally like to see ROC metrics), so I'm concerned about using this in a real use case. Is this slowness expected for plots like this? How could I implement this behavior while retaining a snappy interface, or are there improvements that can be made to the web interface to support these use cases?

**Comment by cvphelps** [comment]
Hi Stef, thanks for reaching out and sharing an example page. I'll circulate this internally and see if we can find a good performance improvement for you.

**Comment by jdanbrown** [comment]
+1 I'm a teammate of @stef-stripe at Stripe. Our ML org at Stripe is evaluating wandb and comet.ml to complement some of our internal model training and evaluation tooling, and our first impressions of wandb are very positive in terms of feature set, functionality, and especially viz customizability, except for this very-slow-UI issue. Currently it looks like a total blocker for us proceeding with wandb, since the web UI is sluggish enough to be effectively unusable by our teams.

Would love to know if we're just doing something off the happy path here? Thanks for any help!

**Comment by jdanbrown** [comment]
Another observation: loading this page pegs ~100% of a core (2019 Macbook Pro) in both Chrome and Firefox. That seems likely a bug on its own? Hopefully easier to investigate and potentially fix than "general slowness".
- https://wandb.ai/stef-stripe/binary-classification-2?workspace=user-stef-stripe

**Comment by cvphelps** [comment]
Hi @jdanbrown @stef-stripe, could we hop on a call on Monday? Would love to get this working well for you — my email is carey@wandb.com

**Comment by shawnlewis** [comment]
Hi folks, we just pushed a fix that improves the page behavior. Custom charts are new, there was an over-zealous rendering bug. There's plenty more to optimize beyond this.

Can you try refreshing the pages and let us know if this first improvement helps?

As Carey said, we've love to talk on Monday.

**Comment by stef-stripe** [comment]
I definitely see an improvement, load times and interface elements on the page are more responsive (say ~1s latency vs ~5s latency on scrolling, hovering, clicking) much better but still very delayed and noticeable. I'm still seeing CPU usage for the tab at 100%.

**Comment by cvphelps** [comment]
Thanks @stef-stripe, could you please shoot me an email at carey@wandb.com so we can talk next week?

**Comment by jdanbrown** [comment]
🎉 Awesome, thank you!!

@shawnlewis Are you able to repro @stef-stripe's 100% cpu behavior on your end? That seems like a (fixable) bug that hopefully is at the root of stef's "but still very delayed and noticeable" observation.

**Comment by shawnlewis** [comment]
I don't see 100% cpu usage, it spikes up to 50% every few seconds. But there is plenty more that we'll fix here to make this fast. You can turn off "auto refresh" if you click your profile picture, that should get rid of the pegged cpu issue for now.

**Comment by shawnlewis** [comment]
@stef-stripe We just deployed a handful of other improvements. The cpu usage issue is fixed, and there are a bunch of other improvements.

Your Vega charts each take about 2s of cpu time to render. There's no low-hanging fruit for reducing that render time. But now we'll only render them once when needed, which makes the UI much more usable.

Can you take a look at let us know how you feel?

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
