### ISSUE TITLE
Setup issue: proxy not forwarding headers properly when trying to use artifacts with local wandb

### ISSUE THREAD

**Issue by rjdp** [wandb/client#1543]
`
ERROR   Thread-34 :1030531 [internal_api.py:upload_file():1212] upload_file exception
400 Client Error: Bad Request for url:
`

upon debugging for actual response body, I got :

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>BadDigest</Code>
    <Message>The Content-Md5 you specified did not match what we received.</Message>
    <Key>rajdeep/dsviz-demo-colab/wandb_artifacts/3/12/a477b63ffd858368c31e10f5def86715</Key>
    <BucketName>local-files</BucketName>
    <Resource>/local-files/rajdeep/dsviz-demo-colab/wandb_artifacts/3/12/a477b63ffd858368c31e10f5def86715</Resource>
    <Region>wandb-local</Region>
    <RequestId>164A6E783DFD7FE9</RequestId>
    <HostId>e3c2fe3d-5ef3-4c3b-bce0-ae64555a0eff</HostId>
</Error>
```

* response status code:  `400`

by the way this is a kubernetes install where the requests are proxied via a standalone (non-k8s) nginx load balancer, (nginx server sits infront of k8s cluster, forwarding requests to nodeports as the cloud provider doesnot support ingress load balancer provisioning)

Thanks :)

**Comment by vanpelt** [comment]
Hey @rjdp this is indicating your proxy is not forwarding all of the headers to our container.  In production settings we would connect the local instance to an external cloud storage bucket such as S3 or GCS which would bypass your proxy.  In your current setup all data is stored in the container and the instance will stop working if it runs out of disk space.  Have you spoken to anyone at W&B about obtaining a license to connect your instance to an external storage bucket?

**Comment by rjdp** [comment]
Thanks @vanpelt , I checked again and confirmed all incoming headers are being forwarded (which is [default](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass_request_headers) in nginx when proxy passing). I am currently pursuing to get it running and evaluate it by running few experiments after which I will look forward for licence. really appreciate the utitlity of wandb and you guys contributing. :)

**Comment by cvphelps** [comment]
Thanks for sharing the fix, I'll close this for now.

**Comment by rjdp** [comment]
@cvphelps sorry for the misunderstanding, I meant to clarify that all request headers were already being forwarded (as thats default behaviour in nginx). the issue still persists. I also tried a running wandb-local outside of kubernetes cluster. I ran following on the server and proxy passed request to 8080 from nginx.

`
docker run --rm -d -v wandb:/vol -p 8080:8080 --name wandb-local wandb/local
` 
proxy pass on nginx :

`
location /  {
	proxy_set_header Host $host;
    proxy_pass http://<server-ip>:8080;
}
`

Let me know if can help with more information. Thanks 👍

**Comment by vanpelt** [comment]
Hey @rjdp can you shell into the container and run the following command?

```
docker run -it wandb-local bash
mc admin trace -v local/
```

While this is running, then attempt to create an artifact in a python shell and paste the output here from the docker container in this ticket.

**Comment by rjdp** [comment]
i have collected the logs in [this](https://gist.github.com/rjdp/42604eb5dcfb935c59c9845a40da2860) gist

**Comment by rjdp** [comment]
Hey @vanpelt , I have collected the logs here in [this](https://gist.github.com/rjdp/42604eb5dcfb935c59c9845a40da2860) gist. Thanks

**Comment by vanpelt** [comment]
Hey @rjdp looking at those logs, it seems by the time the request makes it to minio, the request body has been removed and has a content-length of 0.  This is likely due to your proxy droping post bodies that are larger than the default nginx max post body size which is 1mb.  You can set the following directive in the server block of your nginx proxy which should fix this:

```
  # see https://docs.min.io/docs/setup-nginx-proxy-with-minio.html
  ignore_invalid_headers off;
  client_max_body_size 0;
  absolute_redirect off;
```

**Comment by rjdp** [comment]
Thanks @vanpelt , issue persists after using above nginx config update (you may reproduce this by having nginx infront of wandb-local, in my case nginx and wandb-local are on different servers), i will switch to using non nginx local deployment for now.

**Comment by vanpelt** [comment]
We're actually running nginx inside of the docker container so we know it works when properly configured.  I would try copying the example here:

https://docs.min.io/docs/setup-nginx-proxy-with-minio.html

You can also check your nginx access or error logs to see if it's truncating the post bodies.

**Comment by cvphelps** [comment]
Hey there, we don't have bandwidth to support custom configuration questions for free installs of W&B local. Closing this for now.
