### ISSUE TITLE
[CLI] wandb sync fails to upload reports from crashed scripts (AssertionError)

### ISSUE THREAD

**Issue by piraka9011** [wandb/client#1817]
**Describe the bug**

If I run a script and then terminate it (ex. Ctrl-c) or it crashes for misc. reasons, I cannot use `wandb sync` to reupload the wandb logs.

```sh
$ wandb sync -p <MY-PROJECT> --id <RUN-ID> .

Syncing: https://wandb.ai/<MY-ID>/<MY-PROJECT>/runs/<RUN-ID> ...Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/wandb/sync/sync.py", line 122, in run
    data = ds.scan_data()
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/wandb/sdk/internal/datastore.py", line 131, in scan_data
    record = self.scan_record()
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/wandb/sdk/internal/datastore.py", line 115, in scan_record
    assert checksum == checksum_computed
AssertionError
```

**To Reproduce**

I am training a model using PyTorch Lightning.
This should be reproducible on any example with PTL.

1. Run a train script, passing the wandb logger to the PTL trainer.
```py
from pytorch_lightning.loggers import TensorBoardLogger, WandbLogger
from pytorch_lightning import Trainer
...
# Configure model and data_loader
...
logger = [TensorBoardLogger(save_dir="my_logs", name='lightning_logs')]
logger.append(WandbLogger(project="my_project", log_model=True))

trainer = Trainer(
        ...
        logger=logger
    )
trainer.fit(model, data_loader)
```
2. Kill script midrun
3. Attempt to reupload logs from wandb directory (mines looks like this)

```sh
files
logs
run-<RUN-ID>.wandb
wandb
```

**Expected behavior**

Logs should upload.

**Desktop (please complete the following information):**

Ubuntu 20.04, Python 3.8, wandb 0.10.17

**Additional context**

Maybe I'm not running the sync command properly?
An example in the docs would be really helpful!!

**Comment by raubitsj** [comment]
@piraka9011 Thank you for the report.
This is something we have recently become aware of and have scheduled this for a subsequent release
(preliminary target is 0.10.19)

The issue is that the log is incomplete due to being interrupted.

There are a few parts to the fix:
1. minimize the data that might not be flushed to the disk at the time of the control-c (time and data size based flush)
2. try harder at control-c time to close the file more gracefully
3. let wandb sync handle errors at end of stream
4. give an override that allows sync to ignore all errors and make as much progress as possible

**Comment by piraka9011** [comment]
Thanks for the update. Will wait for the release!

**Comment by piraka9011** [comment]
Reporting that this still occurs in 0.10.19 :/

If there's a beta/branch that has the fix, happy to test.

**Comment by MKorablyov** [comment]
I am experiencing the same issue. Seems meaningful to have it such that even when the run crashes all previous data points  logs could be still  reported (except the one interrupted)

**Comment by alek5k** [comment]
I am having this issue, tested on version 0.10.21

**Comment by afiaka87** [comment]
Also experiencing this issue on `wandb==0.10.2`.

**Comment by jcoholich** [comment]
I am having this same issue trying to upload from a  run that has crashed according to wandb, on wandb version 0.10.25. More context on my issue: 
https://github.com/wandb/client/issues/1526#issuecomment-818763611

**Comment by rubencart** [comment]
Same... is it possible to at least upload non corrupted parts of the logs?

**Comment by LarsVaehrens** [comment]
Facing the same issue with `wandb==0.10.26` and `python==3.7` on Ubuntu 18.04.5 LTS. 

As discussed in https://github.com/wandb/client/issues/1526#issuecomment-731408684 I think my problem is caused by a (sometimes) unstable internet connection. Training continues when wandb has crashed, but when the training run ends or I terminate it early I get the message `wandb: \ 0.00MB of 0.00MB uploaded (0.00MB deduped)` and it hangs until I close the terminal or ctrl+z.

Furthermore it is not possible for me to use `wandb sync`  afterwards to sync the log files that crashed. Here I get the same error as described by @jcoholich

**Comment by vanpelt** [comment]
@LarsVaehrens can you share a debug-internal.log or debug.log file from one of the runs that hangs for you?  We fixed what we thought was the primary hanging issue in 0.10.26 so if you have a debug log from a run with the most recent version that would be really helpful.

**Comment by LarsVaehrens** [comment]
@vanpelt yes of course. I have uploaded debug files from two runs to gists here: [run-20210414_171207-3uz7lzpx](https://gist.github.com/LarsVaehrens/0f1fd9143c8c6112c6257ccb1fb7a31b) and here [run-20210413_183005-d71yos1d](https://gist.github.com/LarsVaehrens/9057112a5600cb1637145535e422bb54). Hope that can help to narrow down the problem.

**Comment by rubencart** [comment]
I have the same problem. Logs for the run: https://gist.github.com/rubencart/7cdc93b66db56ffd55104391c1ac7ad0.

**Comment by rubencart** [comment]
Still cannot sync my run with `wandb sync` because of this AssertionError with wandb version 0.10.28. This run is still running, but marked on wandb.ai as crashed.

**Comment by yhn112** [comment]
@vanpelt @raubitsj 
Sorry to bother you this way, but this issue is very critical for some people (including our team).
If it's possible, could you please share some ideas on it, and probably we can help you with it?

**Comment by vanpelt** [comment]
@yhn112 we have plans to fix the case of syncing a run that is in 'offline' mode while it is running.  This will likely take 1-2 weeks.  We do not intend to support running `wandb sync` on an 'online' run.  If running on sync on offline runs is your usecase, we'll keep the ticket updated here.

**Comment by alek5k** [comment]
I think the majority of peoples use cases for wandb sync in this thread are from online runs that are still running but are reported as crashed and never automatically resynchronize. 


There was a period of time I was experiencing a large amount of packet loss on my network which made every run go into this state (days worth of training lost and unable to synchronise). 


Perhaps it could be useful to take a poll or get some metrics on how the majority of users are running wandb sync? To me it would be more important to not lose data, so if you only plan on supporting offline sync, it would probably mean that all my runs are run offline by default, which kind of reduces the attractiveness of the service to me, and can no longer enjoy the visibility of my training (through wandb at least) to do things like kill runs that aren't working out for one reason or another. 


Just wanted to offer some additional thoughts you might want to take into consideration.

**Comment by piraka9011** [comment]
I don't think support for offline runs makes sense.
I would prefer the WandB team invests time in a solution for online runs since that is technically (one of) the main reason(s) to use WandB (i.e the GUI and dashboard).

While the original issue for me was from a run the crashed, I guess it would be good to re-sync runs that have lost connection, but I don't think that's the `sync` CLI command's responsibility.
Probably something to fix in the core lib.

**Comment by vanpelt** [comment]
I wanted to clarify what I meant by not supporting online runs.  We want you to always be able to run `wandb sync` for online runs after they have completed (in the case that not all data was streamed to the server).  The offline support is only for enabling users to run `wandb sync` on the offline runs while they're running.  

The reason for not supporting calling `wandb sync` on a currently running online run is that it introduces multiple threads trying to sync the same data to our backend which we simply can not support.

@alek5k we 110% agree that wandb should never lose a users data and we're currently working to further battle test and harden all code paths in both online and offline mode to ensure users don't get into a state where data is lost.

**Comment by piraka9011** [comment]
Makes sense @vanpelt, thanks for the clarification.

**Comment by maximilianreimer** [comment]
I experienced the same issue in version 0.10.24. The run is reported as crashed but is actually still running. But when I try to run wandb sync I get the same error. 

The difference here seems to be that the runs is actually still running. During the run a `ConnectionResetError: [Errno 104] Connection reset by peer` accoured. Please find the full stack trace of the exception attached. 
[wandb.log](https://github.com/wandb/client/files/6806899/wandb.log)

**Comment by vanpelt** [comment]
Hey @maximilianreimer the specific error you're seeing seems related to a proxy that the client was connecting through.  We retry the connections for up to 2 hours, but in this case we hit the maximum number of retries which is why the run is marked as crashed.  Version 0.10.33 of the wandb library has better handling of network issues, but I'm not sure it would fix this case.

You should still be able to run `wandb sync path_to_run_dir` to have this run data sent to the server assuming the proxy is accepting connections again.

**Comment by MoritzTaylor** [comment]
Got similar problem like @maximilianreimer. Run is crashed in the dashboard but is actually still running. After wandb sync of those "crashed" runs I also got this error. Furthermore, the config.yaml of the run is completely erased by the sync.

**Comment by vanpelt** [comment]
@MoritzTaylor what version of wandb are you using `wandb --version`?

**Comment by vanpelt** [comment]
@MoritzTaylor can you provide a `debug-internal.log` from a run that's failing to sync?  If you could also share the `.wandb` file that would help us reproduce and debug this.  You can send it to vanpelt@wandb.com

**Comment by sydholl** [comment]
Hi @MoritzTaylor, following up on this thread. Can you send over the `debug-internal.log`?

**Comment by KFCxMcDonalds** [comment]
Why this issue is closed? I also encountered this problem at version 0.17.3 
The network of my lab broked accidentally for about one night, after fixing it, my runs on wandb websites show state: carshed. But my training is still running on server local. After stop my training, I try to use `wandb sync path-to-run` to push model evaluation data to websites, I got AssertionError said checksum invalid.
How to fix this? Or is there some way to let me draw my evaluation plot on my own?
