### ISSUE TITLE
[Q] How to programmatically launch runs belonging to specific sweep

### ISSUE THREAD

**Issue by evfro** [wandb/client#2331]
Following the example in https://github.com/wandb/client/issues/1063#issuecomment-635444635, I'd like to not just create multiple runs in the project, but also to assign them to different sweeps. A use-case scenario: each sweep corresponds to a different model with its own unique set of hyperparameters.

I tried local controller functionality, but it seems to work only with "offline" sweeps, e.g. it doesn't sync them to the project and it doesn't work with sweeps that were created online.

I'd also like to avoid using  `wandb.agent` calls. The reason is that agent imposes certain restrictions on the program logic. In my case, grid-search is controlled by an external program not wandb, and I'd like to control the number of runs  externally and not by setting the `count` argument of the agent. Currently, calling it like this 
```
`wandb.agent(sweepid, function=multi_run_func, count=1)`
```
where `multi_run_func` relaunches runs with `wandb.init(reinit=True)` doesn't behave as expected - **everything gets recorded into a single run**.

On the other hand, when I launch runs with `wandb.agent(sweepid, function=single_run_func, count=n_runs)` from my script, I get a warning message for every new run (i.e., `n_runs` such messages in total) saying:
```
signal only works in main thread of the main interpreter
```
which looks like something that may interfere with the results and/or execution reliability.

So, is there any alternative programmatic way to specify which sweep a run should belong to? Or am I missing something in the configuration of `wandb.agent` call that would allow having `count=1` and still be able to launch multiple runs belonging to a specific sweep? 

Thanks!

P.S. The entire code snippet for demonstrating the problem with calling multiple runs within `wandb.agent`:

```python
import random
import wandb

def single_run():
    with wandb.init(reinit=False):
        wandb.log({'loss': random.random})

def multi_run(n_runs):
    for _ in range(n_runs):
        with wandb.init(reinit=True):
            wandb.log({'loss': random.random})

if __name__ == '__main__':
    n_runs = 5
    sweepid = 'test_entity/test_project/test_sweep'

    print('\n=== Runs controlled by wandb.agent ===\n')
    wandb.agent(sweepid, function=single_run, count=n_runs)


    print('\n=== Runs controlled by provided function ===\n')
    wandb.agent(sweepid, function=lambda: multi_run(n_runs), count=1)
```
This code creates only 6 runs (instead of 10). The first 5 runs are from `single_run` function being called `count=5` times by the agent. The last run is from `multi_run` function, that attempts to create new runs by providing `reinit=True`, but the setting is simply ignored by the agent, which results in all data being overwritten 5 times within a single run. The agent also generated 10 warnings `signal only works in main thread of the main interpreter`. Tested on different wandb versions from 0.10.28 to 0.10.32.

**Comment by vanpelt** [comment]
@evfro the next release of the library due out in the next day or two should fix the interpreter issue.  In the meantime, the simplest solution may be to shell out and call agent as a seperate process.

```
subprocess.check_call(["wandb", "agent", "SWEEP_ID", "--count", "N"])
```

As long as your sweep config specifies a "program" that will run the program and pass in the appropriate arguments.

**Comment by evfro** [comment]
@vanpelt thanks for the quick answer! I'm not sure I understand correctly, by fixing "the interpreter issue" you mean it will no longer print a warning message for each run? Or do you mean that executing the line ` wandb.agent(sweepid, function=lambda: multi_run(n_runs), count=1)` will launch independent runs instead of recording everything into a single run?

**Comment by vanpelt** [comment]
@evfro I think I understand the issue now.  Sweep agents currently assume you'll launch a single run per agent.  This isn't tested, but if you want to run multiple runs you'll need to unset the run_id for every run but the first one, i.e.

```
def multi_run(n_runs):
    for i in range(n_runs):
        if i > 0 and os.environ.get("WANDB_RUN_ID"):
            del os.environ["WANDB_RUN_ID"]
        with wandb.init(reinit=True):
            wandb.log({'loss': random.random()})
```

**Comment by evfro** [comment]
@vanpelt that's a nice idea! Unfortunately, it seems that something still provides the same run_id to subsequent `wandb.init` calls and everything still gets logged into the first run. Do you know if there's any additional local cache of run specifications?

**Comment by vanpelt** [comment]
Hey @evfro we have an example that does something similar to what you want.  This may be helpful: https://github.com/wandb/examples/blob/master/examples/wandb-sweeps/sweeps-cross-validation/train-cross-validation.py

**Comment by evfro** [comment]
@vanpelt thanks! This code, unfortunately, doesn't do exactly what I'm trying to achieve.
When it resets env with `reset_wandb_env` function, information about `sweep_id` is gone as well. All independent runs are then grouped using the `group` argument of the `init` function (see [this line](https://github.com/wandb/examples/blob/d071f0d4ff11064a70dded91ae1cbdb62d9c2e6d/examples/wandb-sweeps/sweeps-cross-validation/train-cross-validation.py#L34)).

So, the result of this code will be multiple runs that belong to the same group within the same project, but not to any particular sweep. In contrast, I'd like to have runs belonging to the specified sweep.

What's really strange here is, if I add sweep related keys "WANDB_SWEEP_ID" and "WANDB_SWEEP_PARAM_PATH" into the `exclude` list of `reset_wandb_env` , after the environment is reset, the `sweep_id` information is no longer present in the run (even though it is still accessible via `os.environ["WANDB_SWEEP_ID"]`).

I tried that on my code, here's a modified snippet that illustrates this strange behavior:
```python
def reset_wandb_env():
    exclude = {
        "WANDB_PROJECT",
        "WANDB_ENTITY",
        "WANDB_API_KEY",
        "WANDB_SWEEP_ID",
        "WANDB_SWEEP_PARAM_PATH",
    }
    for k in os.environ.keys():
        if k.startswith("WANDB_") and k not in exclude:
            del os.environ[k]

def multi_run(n_runs):
    for _ in range(n_runs):
        reset_wandb_env()
        with wandb.init(reinit=True) as run:
            print(f'{os.environ["WANDB_SWEEP_ID"]=}') # checking sweep info here
            print(f'{run.sweep_id=}, {run.id=}') # checking sweep info here
            wandb.log({'loss': random.random()})
```

Running this as previously will print something like:
```
os.environ["WANDB_SWEEP_ID"]='7mtyxnmz'
run.sweep_id=None, run.id='19bprvac'
```

As you can see, `sweep_id` info is present in the env, but it is not assigned to runs anymore. This code generates multiple runs that do not belong to any particular sweep within the project. Basically, removing the "WANDB_RUN_ID" key from env leads to empty `sweep_id` in a run. This is a very strange dependence.

**Comment by evfro** [comment]
In addition to my previous post, if I change the reset command from
```python
reset_wandb_env()
```
to
```python
if i > 0:
    reset_wandb_env()
```
then, once again, everything gets recorded into a single run, although into the specified sweep. So, basically, we discovered only two modes:
1. multiple runs but ignored sweep_id,
2. acknowledged sweep_id but single run.

Neither solve my problem. 🙂

I still really hope that it is possible to have multiple runs that would be all assigned to a user-provided sweep.
