### ISSUE TITLE
pdb: Debugging mode breaks with wandb

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#386]
When a script relies on wandb, it  becomes undebuggable through `python -m pdb myscript.py`

The message I get is `Post mortem debugger finished. The prepare_efa_image.py will be restarted`

With wandb
```
Post mortem debugger finished. The prepare_efa_image.py will be restarted
> /home/ec2-user/prepare_efa_image.py(14)<module>()
-> """
(Pdb) bt
  /home/ec2-user/anaconda3/lib/python3.6/bdb.py(434)run()
-> exec(cmd, globals, locals)
  <string>(1)<module>()
> /home/ec2-user/prepare_efa_image.py(14)<module>()
-> """
(Pdb) bt
  /home/ec2-user/anaconda3/lib/python3.6/bdb.py(434)run()
-> exec(cmd, globals, locals)
  <string>(1)<module>()
> /home/ec2-user/prepare_efa_image.py(14)<module>()
-> """
(Pdb)
```

without wandb
```
ZeroDivisionError: division by zero
{'internal_id': '979440106638', 'internal_alias': 'keyapp', 'region': 'us-west-2', 'zone': 'us-west-2b', 'launch_user': 'yaroslavvb', 'launcher_cmd': 'prepare_efa_image.py', 'worker_conda': '/home/ec2-user/anaconda3/bin/../\n', 'worker_cmd': "prepare_efa_image.py --internal_role=worker '--internal_cmd=bash ~/prepare_efa_image.sh'"}
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/ec2-user/util.py(67)ossystem2()
-> 2/0
(Pdb) bt
  /home/ec2-user/anaconda3/lib/python3.6/pdb.py(1667)main()
-> pdb._runscript(mainpyfile)
  /home/ec2-user/anaconda3/lib/python3.6/pdb.py(1548)_runscript()
-> self.run(statement)
  /home/ec2-user/anaconda3/lib/python3.6/bdb.py(434)run()
-> exec(cmd, globals, locals)
  <string>(1)<module>()
  /home/ec2-user/prepare_efa_image.py(14)<module>()
-> """
  /home/ec2-user/prepare_efa_image.py(114)main()
-> worker()
  /home/ec2-user/prepare_efa_image.py(104)worker()
-> nccl_build('2.4.6', "git checkout v2.4.6-1")
  /home/ec2-user/prepare_efa_image.py(102)nccl_build()
-> extra_env=extra_env)
> /home/ec2-user/util.py(67)ossystem2()
-> 2/0
(Pdb)
```

**Comment by vanpelt** [comment]
We had this working in the past.  I'll try to reproduce!

**Comment by kouroshHakha** [comment]
I also have this issue.

**Comment by cvphelps** [comment]
This was fixed with 0.9.x, but broken again in 0.10.x. Keeping this open until we can deduplicate this pdb issue.

**Comment by ariG23498** [comment]
Hey folks,
Could you all please look into this and revert back?
We would like to close the issue if this is resolved. Thanks! :smile:

**Comment by kouroshHakha** [comment]
Yes, I tried 0.9.7 and pdb breakpoints behave normally there. Although I have a specific usage that does not work on 0.9.7 either. 

```
import sys

def _info(etype, value, tb):
    if hasattr(sys, 'ps1') or not sys.stderr.isatty():
        # we are in interactive mode or we don't have a tty-like
        # device, so we call the default hook
        sys.__excepthook__(etype, value, tb)
    else:
        import pdb
        import traceback
        # we are NOT in interactive mode, print the exception...
        traceback.print_exception(etype, value, tb)
        print()
        # ...then start the debugger in post-mortem mode.
        pdb.post_mortem(tb)


def register_pdb_hook():
    sys.excepthook = _info

register_pdb_hook()
if __name__ == '__main__':
    wandb.init()
    a = 1 / 0 # pdb should trace back to the failed line for debugging but breaks when I use wandb.init()
```

**Comment by ariG23498** [comment]
Hey @kouroshHakha 
Could you give the above script a try with our latest release?
`pip install --upgrade wandb` should do the trick of getting the latest release. Thanks :smile:

**Comment by kouroshHakha** [comment]
> Hey @kouroshHakha
> Could you give the above script a try with our latest release?
> `pip install --upgrade wandb` should do the trick of getting the latest release. Thanks 😄

I updated to 0.10.18, it still does not trace back to the failed line. However, it printed the following stuff:
```
WARNING: Logging before flag parsing goes to stderr.
I0208 17:26:04.943697 123145397706752 meta.py:34] meta init
I0208 17:26:04.943941 123145397706752 meta.py:48] meta init done
I0208 17:26:04.944025 123145397706752 meta.py:190] probe
I0208 17:26:04.945592 123145397706752 meta.py:180] setup git
I0208 17:26:04.997829 123145397706752 meta.py:187] setup git done
I0208 17:26:04.998562 123145397706752 meta.py:52] save pip
I0208 17:26:04.999948 123145397706752 meta.py:66] save pip done
I0208 17:26:05.000167 123145397706752 meta.py:231] probe done
I0208 17:26:05.005177 123145397706752 handler.py:94] handle_request: status
I0208 17:26:05.005550 123145387196416 sender.py:117] send: request
I0208 17:26:05.006012 123145387196416 sender.py:126] send_request: status
I0208 17:26:05.009151 123145397706752 handler.py:94] handle_request: poll_exit
I0208 17:26:05.155005 123145387196416 sender.py:117] send: telemetry
I0208 17:26:05.279485 123145387196416 sender.py:117] send: exit
I0208 17:26:05.279756 123145387196416 sender.py:195] handling exit code: 1
I0208 17:26:05.280222 123145387196416 sender.py:203] send defer
I0208 17:26:05.280385 123145387196416 sender.py:117] send: request
I0208 17:26:05.280519 123145387196416 sender.py:126] send_request: poll_exit
I0208 17:26:05.280755 123145387196416 sender.py:117] send: files
I0208 17:26:05.280881 123145387196416 sender.py:682] saving file wandb-metadata.json with policy now
I0208 17:26:05.281306 123145397706752 handler.py:94] handle_request: defer
I0208 17:26:05.281450 123145397706752 handler.py:108] handle defer: 0
I0208 17:26:05.282030 123145387196416 sender.py:117] send: request
I0208 17:26:05.282248 123145387196416 sender.py:126] send_request: defer
I0208 17:26:05.282451 123145387196416 sender.py:212] handle sender defer: 0
I0208 17:26:05.282592 123145387196416 sender.py:248] send defer: 1
I0208 17:26:05.282939 123145397706752 handler.py:94] handle_request: defer
I0208 17:26:05.283061 123145397706752 handler.py:108] handle defer: 1
I0208 17:26:05.352757 123145387196416 sender.py:117] send: request
I0208 17:26:05.353455 123145387196416 sender.py:126] send_request: defer
I0208 17:26:05.353873 123145387196416 sender.py:212] handle sender defer: 1
I0208 17:26:05.354069 123145387196416 sender.py:248] send defer: 2
I0208 17:26:05.354351 123145387196416 sender.py:117] send: stats
I0208 17:26:05.355284 123145397706752 handler.py:94] handle_request: defer
I0208 17:26:05.355540 123145397706752 handler.py:108] handle defer: 2
I0208 17:26:05.355957 123145387196416 sender.py:117] send: request
I0208 17:26:05.356204 123145387196416 sender.py:126] send_request: defer
I0208 17:26:05.356575 123145387196416 sender.py:212] handle sender defer: 2
I0208 17:26:05.356803 123145387196416 sender.py:248] send defer: 3
I0208 17:26:05.357393 123145397706752 handler.py:94] handle_request: defer
I0208 17:26:05.357614 123145397706752 handler.py:108] handle defer: 3
I0208 17:26:05.357999 123145387196416 sender.py:117] send: summary
I0208 17:26:05.359266 123145387196416 sender.py:682] saving file wandb-summary.json with policy end
I0208 17:26:05.359946 123145387196416 sender.py:117] send: request
I0208 17:26:05.360193 123145387196416 sender.py:126] send_request: defer
I0208 17:26:05.360389 123145387196416 sender.py:212] handle sender defer: 3
I0208 17:26:05.360634 123145387196416 sender.py:248] send defer: 4
I0208 17:26:05.361661 123145397706752 handler.py:94] handle_request: defer
I0208 17:26:05.362044 123145397706752 handler.py:108] handle defer: 4
I0208 17:26:05.362567 123145387196416 sender.py:117] send: request
I0208 17:26:05.362883 123145387196416 sender.py:126] send_request: defer
I0208 17:26:05.363247 123145387196416 sender.py:212] handle sender defer: 4
I0208 17:26:05.816304 123145387196416 sender.py:248] send defer: 5
I0208 17:26:05.817769 123145397706752 handler.py:94] handle_request: defer
I0208 17:26:05.818074 123145397706752 handler.py:108] handle defer: 5
I0208 17:26:05.824038 123145387196416 sender.py:117] send: request
I0208 17:26:05.834042 123145387196416 sender.py:126] send_request: defer
I0208 17:26:05.838109 123145387196416 sender.py:212] handle sender defer: 5
I0208 17:26:05.838320 123145387196416 sender.py:248] send defer: 6
I0208 17:26:05.840763 123145397706752 handler.py:94] handle_request: defer
I0208 17:26:05.841044 123145397706752 handler.py:108] handle defer: 6
I0208 17:26:05.841249 123145387196416 sender.py:117] send: request
I0208 17:26:05.841367 123145387196416 sender.py:126] send_request: defer
I0208 17:26:05.841485 123145387196416 sender.py:212] handle sender defer: 6
I0208 17:26:06.025797 123145387196416 sender.py:248] send defer: 7
I0208 17:26:06.026400 123145397706752 handler.py:94] handle_request: defer
I0208 17:26:06.026504 123145397706752 handler.py:108] handle defer: 7
I0208 17:26:06.026640 123145387196416 sender.py:117] send: request
I0208 17:26:06.026714 123145387196416 sender.py:126] send_request: defer
I0208 17:26:06.026797 123145387196416 sender.py:212] handle sender defer: 7
I0208 17:26:06.026901 123145387196416 sender.py:248] send defer: 8
I0208 17:26:06.027271 123145397706752 handler.py:94] handle_request: defer
I0208 17:26:06.027362 123145397706752 handler.py:108] handle defer: 8
I0208 17:26:06.027459 123145387196416 sender.py:117] send: final
I0208 17:26:06.027695 123145387196416 sender.py:117] send: footer
I0208 17:26:06.027776 123145387196416 sender.py:117] send: request
I0208 17:26:06.027845 123145387196416 sender.py:126] send_request: defer
I0208 17:26:06.027909 123145387196416 sender.py:212] handle sender defer: 8
I0208 17:26:07.284185 123145397706752 handler.py:94] handle_request: poll_exit
I0208 17:26:07.284890 123145387196416 sender.py:117] send: request
I0208 17:26:07.285168 123145387196416 sender.py:126] send_request: poll_exit
wandb:                                                                                
I0208 17:26:07.289476 123145397706752 handler.py:94] handle_request: get_summary
I0208 17:26:07.290390 123145397706752 handler.py:94] handle_request: sampled_history
I0208 17:26:07.291213 123145397706752 handler.py:94] handle_request: shutdown
I0208 17:26:07.291432 123145397706752 handler.py:333] shutting down handler
...
```

**Comment by ziqi-zhang** [comment]
I met a similar issue. After initialized wandb there are some problems in the interactive mode. I can not use up button (got ^[[A) or Home button. When I downgrade wandb to 0.9.7 there is no problem but in the later versions (0.10.18 and 0.10.17) the problem exists.

**Comment by karthi0804** [comment]
Hi, it happens in 0.10.21 also. any workaround or fix?

**Comment by vanpelt** [comment]
0.10.23 may have fixed this, can you try upgrading.  The other thing to try would be setting the environment variable `WANDB_CONSOLE=off`.  If it's still not working, please provide a code snippet to reproduce.

**Comment by karthi0804** [comment]
> 0.10.23 may have fixed this, can you try upgrading. The other thing to try would be setting the environment variable `WANDB_CONSOLE=off`. If it's still not working, please provide a code snippet to reproduce.

I upgraded to 0.10.23 and set WANB_CONSOLE=off. Still I get this error,

```
$ python -m pdb main.py -c config.ini --mode train
> /home/karthi/Documents/Work/sw/intentionprediction/main.py(1)<module>()
-> import matplotlib
(Pdb) b pl_module.py:88
Breakpoint 1 at /home/karthi/Documents/Work/sw/intentionprediction/pl_module.py:88
(Pdb) c
Global seed set to 0
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Global seed set to 0
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/1
Problem at: /home/karthi/venv_lyft/lib/python3.7/site-packages/pytorch_lightning/loggers/wandb.py 163 experiment
Traceback (most recent call last):
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 745, in init
    run = wi.init()
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 421, in init
    backend.ensure_launched()
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/wandb/sdk/backend/backend.py", line 125, in ensure_launched
    self.wandb_process.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 172, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 745, in init
    run = wi.init()
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 421, in init
    backend.ensure_launched()
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/wandb/sdk/backend/backend.py", line 125, in ensure_launched
    self.wandb_process.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 172, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/pdb.py", line 1699, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.7/pdb.py", line 1568, in _runscript
    self.run(statement)
  File "/usr/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/karthi/Documents/Work/sw/intentionprediction/main.py", line 199, in <module>
    main()
  File "/home/karthi/Documents/Work/sw/intentionprediction/main.py", line 64, in main
    train(cp)
  File "/home/karthi/Documents/Work/sw/intentionprediction/main.py", line 113, in train
    trainer.fit(pl_model, train_dataloader=train_loader, val_dataloaders=[val_loader, tb_loader])
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 496, in fit
    self.pre_dispatch()
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 530, in pre_dispatch
    self.logger.log_hyperparams(self.lightning_module.hparams_initial)
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py", line 42, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pytorch_lightning/loggers/wandb.py", line 184, in log_hyperparams
    self.experiment.config.update(params, allow_val_change=True)
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pytorch_lightning/loggers/base.py", line 41, in experiment
    return get_experiment() or DummyExperiment()
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py", line 42, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pytorch_lightning/loggers/base.py", line 39, in get_experiment
    return fn(self)
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pytorch_lightning/loggers/wandb.py", line 163, in experiment
    ) if wandb.run is None else wandb.run
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 782, in init
    six.raise_from(Exception("problem"), error_seen)
  File "<string>", line 3, in raise_from
Exception: problem
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> <string>(3)raise_from()
(Pdb) 
```

**Comment by vanpelt** [comment]
Thanks for the traceback @karthi0804.  We'll need to do some more digging to understand the root cause.  In the meantime there are two workarounds:

1. Try setting the following environment variable: `WANDB_START_METHOD=thread` (this will tell us to spin up threads in the current process instead of launching a separate logging process)
2. You can disable wandb entirely with `WANDB_MODE=disabled` (this will stub out our api's and not actually log data)

**Comment by cemoody** [comment]
I've gotten the same issue and I can confirm that `WANDB_START_METHOD=thread` at least avoided it!
