### ISSUE TITLE
Using a proxy with wandb 

### ISSUE THREAD

**Issue by ankeshanand** [wandb/client#555]
Hi,

Is it possible to use a proxy with wandb? I tried monkeypatching with pysocks (https://github.com/Anorov/PySocks#monkeypatching) but didn't work.

**Comment by ankeshanand** [comment]
Looked a bit more into to see if it was possible to pass the socks proxy to the library making network calls. 

* It seems you are using `gql` which in-turn uses requests. `gql` doesn't seem to be maintained anymore and doesn't support passing `kwargs` into the `RequestsHTTPTransport` call. (https://github.com/graphql-python/gql/pull/45)

**Comment by vanpelt** [comment]
Because it's using the requests library under the hood.  You should be able to configure a proxy by setting the HTTPS_PROXY header in your environment, can you try that?

```bash
export HTTPS_PROXY="http://10.10.1.10:1080"
```

https://2.python-requests.org/en/master/user/advanced/#proxies

**Comment by silent567** [comment]
Hi, I am also wondering how to use proxy with wandb. Is there any successful solution? Thanks!

**Comment by vanpelt** [comment]
Have you tried setting the HTTPS_PROXY environment variable?

**Comment by silent567** [comment]
Haven't yet. We need administrators ' permission before any changes. I am not sure if this global configuration will affect other users...

**Comment by vanpelt** [comment]
You can configure the PROXY in your python script before calling wandb.init:

`os.environ["HTTPS_PROXY"] = "XXX"` to have it only effect your training process.

**Comment by silent567** [comment]
Great, I will try it when necessary. Currently, the administrators have made some configurations of the internet to support my usage of wandb. So problem solved in another way. Thanks!

**Comment by ariG23498** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen. :smile:

**Comment by denisbeslic** [comment]
Hi,

I'm using PyTorch Lightning (v=2.0.0) and WandB (v=0.15.0). I get multiple error messages from urllib3 and wandb. 

```
INFO:wandb.sdk.lib.retry:Retry attempt failed
[...]
OSError: Tunnel connection failed: 403 Forbidden
[...]
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
[...]
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden'))'.
[...]
wandb: ERROR Run initialization has timed out after 60.0 sec.
```

After using the changing the HTTPS_PROXY environment variable the errors from urllib3 disappear, but wandb still throws the following error:
```
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: Network error (ProxyError), entering retry loop.
wandb: Network error (ProxyError), entering retry loop.
Problem at: /.../lib/python3.10/site-packages/pytorch_lightning/loggers/wandb.py 405 experiment
wandb: ERROR Run initialization has timed out after 60.0 sec.
```

I also tried setting it via `os.environ["HTTPS_PROXY"] = "XXX"` before using `wandb_logger = WandbLogger()` but that does not make a difference either.

**Comment by mmlynarik** [comment]
I have the same problem as @denisbeslic

**Comment by denisbeslic** [comment]
Setting the https_proxy variables solved the problem for me 
```
export HTTPS_PROXY="http://your_proxy:your_proxy_port"
export https_proxy="http://your_proxy:your_proxy_port"
```
